version: '2'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    depends_on:
    - mongodb

  mongodb:
    image: mongo:3.2.20-jessie
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
